services:
  app:
    image: node:24.15
    working_dir: /stocks
    container_name: stocks_app
    command: sh -c "npm run start"
    ports:
      - "9229:9229"
    env_file: variables.env
    volumes:
      - .:/stocks
